#'Generate background data for IOS calculation
#'
#' \code{background_ids} Returns list of IDs of available GWAS summary statistics. The data is obtained from [IEU GWAS database](https://gwas.mrcieu.ac.uk/).
#' 
#' @param id_exp ID for the exposure in IEU GWAS database. 
#' @param id_out ID for the outome in IEU GWAS database.
#' @param type Set a default list of IDs. 
#' *`default`: Returns list of IDs of GWAS summary statistics generated by many different consortia and generated from UKB.
#' *`advanced`: In addition to the default list, it returns list of IDs of GWAS summary data on protein, metabolite, and eQTL levels, as well as GWAS summary statistics imported from the EBI database.
#' @examples background_ids(id_exp=id_exp, id_out=id_out, type="default")
#' 
#' 
#' \code{make_background} Generates harmonised dataset of SNP-exposure and SNP-other traits that are possibly associated with suspicious SNPs. It also calculates R squared of SNP-exposure and/or SNP-other traits.
#' @param exp Dataset of the instruments for the exposure, obtained using \code{extract_instruments}
#' @param id_bg List obtained using \code{background_ids}
#' @examples make_background(exp = exp_dat, id_bg = id_bg)
#'
#' @export
#' @return Data frame

# choose background dataset list
background_ids <- function(id_exp=id_exp, id_out=id_out, type=c("default", "advanced")[1]){
  ao <- suppressMessages(TwoSampleMR::available_outcomes())
  if(type[1] == "default") {
    ids <- subset(ao) %>%
      arrange(desc(sample_size)) %>%
      filter(nsnp > 100000) %>%
      filter(!duplicated(trait), mr == 1) %>%
      filter(grepl("ukb-b|ieu-a", id)) %>%
      filter(! id %in% c(id_exp, id_out))
    
    ids <- subset(ids, !(category == "NA" & unit == "NA"))
    id_list <- ids$id 
    
    message("Using default list of ", nrow(ids), " traits")
  }
  
  if(type[1] == "advanced"){
    ids <- subset(ao) %>%
      arrange(desc(sample_size)) %>%
      filter(nsnp > 100000) %>%
      filter(!duplicated(trait), mr == 1) %>%
      filter(!grepl("ukb-a", id)) %>%
      filter(! id %in% c(id_exp, id_out))
    
    ids <- subset(ids, !(category == "NA" & unit == "NA"))
    id_list <- ids$id 
    
    message("Using default list of ", nrow(ids), " traits")
  }
  
  return(id_list)
  
}




# make background dataset
#bg_dat <- make_background(snplist = exp_dat$SNP, id_bg = id_bg)
make_background <- function(exp = exp_dat, id_bg = id_bg) {
  #-----------------------------------------------------------------------------------------------------
  #Generate background dataset which includes phenotypes associated with outliers (suspicious SNPs).
  snplist <- exp$SNP
  bdat <- TwoSampleMR::extract_outcome_data(snps = snplist, outcomes = id_bg)
  
  
  #Retrive info of "sample_size", "ncase", "ncontrol", "unit", "sd" (category?) from IEU GWAS database
  bdat <- TwoSampleMR::add_metadata(bdat, cols = c("sample_size", "ncase", "ncontrol", "unit", "sd"))
  exp <- TwoSampleMR::add_metadata(exp, cols = c("sample_size", "ncase", "ncontrol", "unit", "sd"))
  
  #-----------------------------------------------------------------------------------------------------
  #Data cleaning:: Remove rows if both of units and sd are missing to calculate R squared
  remove_na_dat <- function(dat = dat, what = "outcome"){
    if(length(unique(dat[[paste0("units.", what)]])) >= 1)
    {
      dat <- subset(dat, !(dat[[paste0("units.", what)]] == "NA") |!is.na(dat[[paste0("sd.", what)]]))
    }
    return(dat)
  }
  
  bdat <- remove_na_dat(bdat, "outcome")
  exp <- remove_na_dat(exp, "exposure")
  
  #-----------------------------------------------------------------------------------------------------
  #Caculate R square
  bdat <- add_rsq(bdat)
  exp <- add_rsq(exp)
  
  #-----------------------------------------------------------------------------------------------------
  #Merge two datasets - exposure data and background data
  bdat <- merge(bdat, subset(exp, select=c(SNP, rsq.exposure), by="SNP"))
  bdat$r2_ratio <- bdat$rsq.outcome / bdat$rsq.exposure
  
  return(bdat)
  
}


